# Generated by Django 5.1 on 2024-09-05 18:44

import authentication.auth_enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(authentication.auth_enums.UserRole['LOAN_PROVIDER'], 'LOAN_PROVIDER'), (authentication.auth_enums.UserRole['LOAN_CUSTOMER'], 'LOAN_CUSTOMER'), (authentication.auth_enums.UserRole['BANK_STAFF'], 'BANK_STAFF')], default=authentication.auth_enums.UserRole['LOAN_CUSTOMER'], max_length=20),
        ),
    ]
